spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dlyk
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis:
  mapper-locations: classpath:/mappers/*.xml
