spring:
  application:
    name: springsecurity-02-db-login
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dlyk
mybatis:
  mapper-locations: classpath:/mappers/*.xml
